### ISSUE TITLE
Resolve all ESLint errors

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#10]
@JoshuaVSherman commented on [Sat Apr 08 2017](https://github.com/WebJamApps/web-jam-front/issues/167)

@JoshuaVSherman commented on [Tue Feb 21 2017](https://github.com/WebJamApps/ourhandsandfeet/issues/313)

**Comment by TheR3dErik** [comment]
Issue moved to [WebJamApps/web-jam-back #76](https://github.com/WebJamApps/web-jam-back/issues/76) via [**ZenHub**](https://www.zenhub.com/)
