### ISSUE TITLE
Finish Jest Tests for React

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1136]
All files | 95.96 | 92.86 | 87.5 | 97.94 |

**Comment by DannyMcwaves** [comment]
Hi @JoshuaVSherman 
 for the webpack-cli warning, please have a look at this thread, https://github.com/webpack/webpack-cli/issues/287
Also, should I upgrade materi-ui beta?

**Comment by JoshuaVSherman** [comment]
Ok I'll try to look at it tonight, sure update material UI. If the webpack
warnings can wait till next month, that it also fine, thanks

**Comment by JoshuaVSherman** [comment]
https://github.com/aurelia/tools/pull/62/files

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman fixed. closing now so I can merge.
