### ISSUE TITLE
music player has some minor issues to fix please

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1161]
* console error when youtube, please fix:
www-widgetapi.js:99 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://web-jam-back-dev.herokuapp.com').

* text alignment on 'Copy Url' button, please fix
![image](https://user-images.githubusercontent.com/13340120/42726772-e4b4bafa-8767-11e8-9665-99963b4bbc9a.png)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I have no idea what's causing this, but I'm still looking into it.
