### ISSUE TITLE
Event scheduling time clock picker is still not working correctly, please fix asap

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1162]
* 7:02 am inserted 12:02 am into the form

![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/9f5a6132-a341-4931-b63d-1f01fb9957d4)

@DannyMcwaves 
* also, clicking update event and times do not fill into the form, it is just blank, please fix
![image](https://user-images.githubusercontent.com/13340120/42728460-e7dab196-8788-11e8-80a7-261149179b60.png)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman 

I set my timezone to Virginia local time.

<img width="508" alt="screen shot 2018-07-14 at 6 59 42 pm" src="https://user-images.githubusercontent.com/16429468/42729005-2d48385c-8798-11e8-8b59-c2197a294839.png">

couldn't reproduce  it.

I was testing on https://web-jam.com/dashboard/vol-ops/5b4a7f6c7af85b0004b7bd96

**Comment by JoshuaVSherman** [comment]
Um happens every time, am only, please try again

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves the first issue was fixed, thanks you, but the second issue still remains with respect to the update form does not display the times, it is blank, please fix

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman yes. that is true.

First of all, the react component is rendered when the aurelia stack is mounted. Hence, any changes in variables outside of the react component does not re-render the component, hence the data that is passed to the component during start time is not bound.

Also, there are default values inside the form, but you asked for the form to blank.

My observations thus far.

**Comment by JoshuaVSherman** [comment]
What matters is what is being perceived by the user. You could overlay the
value fetched from db on top of the form field, then hide it after they
click to initiate the clock ui
