### ISSUE TITLE
Now the slide shows on home page and music page are screwed up, they obviously need their own styles or something, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#121]
I see no improvement here, the text overlapps the graphic and there is white space above the graphic now, please fix:

![image](https://cloud.githubusercontent.com/assets/13340120/25076231/c6ca08c8-22ec-11e7-9513-cb2fefaab97b.png)

**Comment by Coletrane** [comment]
What are the slides on the homepage supposed to be?

**Comment by JoshuaVSherman** [comment]
I'm away from my computer now, but I think if you view them in different
widths, you will see the issues
