### ISSUE TITLE
Create a music player for /music/pub

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1266]

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please remove 
* Learn to Fly 
* Old Black Water
These songs will be coming from dropbox, we will no longer be using the 'your listen' site.
thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I have taken out the urls from the config.json object. should I remove the players for the songs from the main page?

**Comment by JoshuaVSherman** [comment]
No, leave them for now, thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves song titles and artists please fix
* I Still Haven't Found What I'm Looking For by U2 - Josh & Maria Sherman
* Cups (when i'm gone) by A. P. Carter - Josh & Maria Sherman
* I'm Yours by Jason Mraz - Josh & Maria Sherman
