### ISSUE TITLE
Volops Dashboard, after schedule event, try to schedule a second event, checkboxes select all, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1323]
![image.png](https://images.zenhubusercontent.com/56be23566caf56c9d38c78ce/efd6b43a-86c3-4a40-a74c-25542517c988)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I'm having a hard time reproducing this issue. 

If I'm scheduling a new event right after a previously scheduled one, the checkboxes are empty.

**Comment by JoshuaVSherman** [comment]
If you forced a page reload after submit, this should be fixed. I'll check

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves this is still not working properly, now the submit button is missing.
This is if I try to schedule two events one after the other one from the dashboard/vol-ops
Then after a little bit of time passes, the submit button does display
there is some delay or glitch here, maybe just reloading the page after submit would fix it?

**Comment by DannyMcwaves** [comment]
Hi @JoshuaVSherman 

Could you also check and close this event. thanks. 
https://www.useloom.com/share/147a07fda85549c8a3dc9aa8a768143d

**Comment by JoshuaVSherman** [comment]
Hey Danny, yes I merged your code for the our hands and feet slideshow.
There are others to do too
