### ISSUE TITLE
refactor picture slideshows

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1326]
* [x] refactor to be a react component
* [x] update the /ohaf slideshow
* [x] update the /library slideshow
* [x] update the /music slideshow

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please ping me when you are ready to start and if needing more discussion, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman how about this react component? 

https://github.com/Pau1fitz/react-slidez

**Comment by JoshuaVSherman** [comment]
Ok seems fine, thanks

**Comment by DannyMcwaves** [comment]
hi @JoshuaVSherman I made a commit for this one some time ago, could you check it out and close it.
