### ISSUE TITLE
Use browserstack to test the login from yahoo email when on an iphone and Safari

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1351]
I think possibly some of our code is not compatible with Safari
create a yahoo email address for testing
login using the yahoo email (not google)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman how exactly did you test with a yahoo mail? 

The `Google login` can only accept a valid google account. Yahoo emails are from different domains and organization.

**Comment by JoshuaVSherman** [comment]
You need to sign up for a Yahoo email, then go to our web-jam/register page
and use it there

**Comment by DannyMcwaves** [comment]
<img width="567" alt="screen shot 2019-02-24 at 4 51 05 pm" src="https://user-images.githubusercontent.com/16429468/53302242-67b78700-3854-11e9-9e7a-58f44f722355.png">

<img width="691" alt="screen shot 2019-02-24 at 4 50 44 pm" src="https://user-images.githubusercontent.com/16429468/53302243-67b78700-3854-11e9-87a5-664929e6cc46.png">



When you register, you get a verify link with a 5-figure verify code. there however, is not button to click to verify the email.

The screenshots above shows the verify sample on iOS safari and Mac chrome.

**Comment by JoshuaVSherman** [comment]
Ok so there is a problem,  I'll look into that, thanks
