### ISSUE TITLE
URLSearchParams is not supported in iOS, so fix in all places, then test again with browserstack

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#1366]
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I have tested the latest push for this on iOS. I haven't had any bugs so far.
Is there something specific I should be testing?

**Comment by JoshuaVSherman** [comment]
No that's it thanks
