### ISSUE TITLE
I can either have the table scroll or the filter not breaking the table, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#160]
<div class="search-table-outer" style="position:relative;overflow-x:visible;">

@joshstoro this issue here could also be the reason why I had to inline a bunch of styles yesterday or why we can't get the css working as it already does on our other project, cstlibrary
https://github.com/aurelia/skeleton-navigation/pull/714#issuecomment-296149656

**Comment by JoshuaVSherman** [comment]
@joshstoro 
Hey, if I don't hear back from you by end of day tomorrow (Friday, May 5), then i'm going to assume you are not going to fix this issue, and I'll either work on it myself some more or find another developer to help me with it.
Congrats on your graduation, we will be at the ceremony on Saturday,

**Comment by joshstoro** [comment]
See commit 7df7431 on storobranch. Added iron dropdown as the wrapper. Now properly displays over table. On super small window sizes table was not scrollable. Could be Chrome. If this is an issue that needs to be looked at i can do some digging.

**Comment by JoshuaVSherman** [comment]
@joshstoro Good morning Josh. Thank you for volunteering to fix this issue with the data table. However, there are a few things that I need you to do please before I am able to review and merge your code as follows:

* Your branch was out of date with the base branch, "dev". Please be sure
to *git pull origin dev*

* If any automated tests are failing (currently it is okay), then please update any related unit or e2e test.

* After completing the above items, push your code to GitHub again in your branch and then
submit a Pull Request (to base branch, dev).
 - In the pull request, set me as a reviewer.
 - In the pull request, set this issue #160 as a linked issue.

Thanks again, and i'm looking forward to reviewing your pull request.
have a great day!

Josh Sherman
Ping me on Hangouts if you need any assistance.
