### ISSUE TITLE
Get the protractor tests to run in CircleCI (they run locally without error)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#187]
[protractor] [18:54:00] E/runner - Unable to start a WebDriver session.
[protractor] [18:54:01] E/launcher - Error: SessionNotCreatedError: session not created exception: Chrome version must be >= 56.0.2884.0
[protractor]   (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.13.0-116-generic x86_64)
[protractor]     at Object.checkLegacyResponse (/home/ubuntu/combined-front/node_modules/selenium-webdriver/lib/error.js:505:15)
[protractor]     at parseHttpResponse (/home/ubuntu/combined-front/node_modules/selenium-webdriver/lib/http.js:509:13)
[protractor]     at doSend.then.response (/home/ubuntu/combined-front/node_modules/selenium-webdriver/lib/http.js:440:13)
[protractor]     at process._tickCallback (internal/process/next_tick.js:109:7)
[protractor] [18:54:01] E/launcher - Process exited with error code 100
[protractor] The script called "e2e.protractor" which runs "nps e2e.protractor.install && protractor test/protractor.conf.js" failed with exit code 100 https://github.com/kentcdodds/nps/blob/v5.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[protractor] The script called "e2e.whenReady" which runs "wait-on --timeout 120000 http-get://localhost:19876/index.html && nps e2e.protractor" failed with exit code 100 https://github.com/kentcdodds/nps/blob/v5.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[protractor] nps e2e.whenReady exited with code 100
--> Sending SIGTERM to other processes..
[webpack] webpack-dev-server --inline --port=19876 exited with code null
The script called "e2e" which runs "node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "webpack,protractor" 'webpack-dev-server --inline --port=19876' 'nps e2e.whenReady' --kill-others --success first" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code

**Comment by LinuxBozo** [comment]
@JoshuaVSherman https://github.com/chronogolf/circleci-google-chrome

**Comment by LinuxBozo** [comment]
Above should fix based on the error that you are seeing:
`[protractor] [18:54:01] E/launcher - Error: SessionNotCreatedError: session not created exception: Chrome version must be >= 56.0.2884.0`
