### ISSUE TITLE
Code quality tools are enabled

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#226]

**Comment by LinuxBozo** [comment]
Just FYI, I haven't fully integrated Code Climate yet, and there is lots of things to do there, but it will keep track of code quality (duplication, complexity, etc) and test coverage metrics over time to give an overall quality metric of the codebase.

**Comment by JoshuaVSherman** [comment]
awesome, i'll read into it
I assumed it was something you started, thanks

**Comment by LinuxBozo** [comment]
Ok, Code Climate, Snyk.io (security checking) and Houndci.com (checks style) are now all setup for pull requests. This should keep code cleaner.

**Comment by JoshuaVSherman** [comment]
Have you heard of pretify, I was reading about it the other night?
