### ISSUE TITLE
Decide if we should start writing our unit tests with Jest or not, sounds better according to the aurelia-esnext-webpack project

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#237]
https://github.com/aurelia/skeleton-navigation/commit/bf8a8cd8b6307f6a704c961655a4670e316637e7

@LinuxBozo 
commits since april 30th were for using jest with karma, maybe we should do this so we are being consistant with the skeleton project?
![image](https://cloud.githubusercontent.com/assets/13340120/25580230/36b43440-2e4d-11e7-9f98-f4f7c8c1d4c7.png)

**Comment by LinuxBozo** [comment]
It wasn't for using with, it was parity between the two, so you could use either, and they test the same things (the unify comment)
