### ISSUE TITLE
Ask Maria to talk to Phifer about another student for ourhandsandfeet JavaScript coding

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#239]
@chemmom2 this is not important to do right away, but whenever you get a change, please follow up with Phifer regarding the student she thinks is interested in OHAF JavaScript development, thanks

**Comment by JoshuaVSherman** [comment]
@chemmom2 hey, what is Phifer's email and phone number please

**Comment by chemmom2** [comment]
I don't think I have a phone number for her, but here are two email
addresses:

pherrala@rcs.k12.va.us

phifer@gmail.com
