### ISSUE TITLE
I need to set permissions for my linux computer so that it runs without sudo

### ISSUE THREAD

**Issue by TheR3dErik** [WebJamApps/combined-front#251]
I keep having to sudo everything and it's getting on my nerves.

Have tried:
Setting permissions on user folder to 755

Have not tried:
Asking on stackoverflow
Gitter
A lot of research

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Hey, what is the status of this issue? It would be nice to have it fixed before we pair on Saturday

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Hey, you can close this issue whenever you believe that your Linux permissions are fixed.
