### ISSUE TITLE
Get Karma debugger working

### ISSUE THREAD

**Issue by TheR3dErik** [WebJamApps/combined-front#326]
https://glebbahmutov.com/blog/debugging-karma-unit-tests/

**Comment by JoshuaVSherman** [comment]
@LinuxBozo I could also really use some training on debugging unit tests, and i'm not sure if the karma debugger is even working anymore

**Comment by LinuxBozo** [comment]
First, merge #349, where I fixed both your test, and stripping out coverage info when running debug, then do:
 - `npm run test:debug` in console
 - click `DEBUG` button in Chrome window that opens
 - Open `Developer Tools` in new window that is launched
 - Click `Sources` tab
 - Expand `webpack://`
 - Expand `.`
 - Click file, set breakpoint, etc..

<img width="555" alt="screen shot 2017-05-24 at 7 22 24 pm" src="https://cloud.githubusercontent.com/assets/723420/26429720/890bbf76-40b6-11e7-8d34-8163832a52b4.png">
