### ISSUE TITLE
Create web form for new charity

### ISSUE THREAD

**Issue by TheR3dErik** [WebJamApps/combined-front#327]
Use librarian as example

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Hey where is your pull request, it was working last night!?

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Good afternoon, just wondering when you are going to push up some code and a pull request for me to review? I saw something working on Wednesday

**Comment by JoshuaVSherman** [comment]
@erik pull request!?

**Comment by JoshuaVSherman** [comment]
@TheR3dErik pull request!?
