### ISSUE TITLE
npm run test:debug is no longer working as expected, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#398]
Updated our developers guide to say that you need to scroll up in the Chrome to see the DEBUG button.

**Comment by JoshuaVSherman** [comment]
@LinuxBozo Hey, if you have some time today, I could really use your help to figure out why the Karma debugger is no longer working. It just shows 100 percent coverage and Chrome does not display the debug button, and if I go to the sources, there are no tests there anymore. Thanks in advance.

**Comment by LinuxBozo** [comment]
@JoshuaVSherman Looks fine to me. I has to scroll up to get the debug button through, as it was showing the lower half of the window for some reason.

**Comment by JoshuaVSherman** [comment]
Well that's it then, I didn't scroll up, weird, thanks
