### ISSUE TITLE
Form validation for new charity form

### ISSUE THREAD

**Issue by TheR3dErik** [WebJamApps/combined-front#406]

**Comment by JoshuaVSherman** [comment]
@TheR3dErik The charity needs to store an array of the user ids for the managers as well as their names. The user id is a unique key. Thanks

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Please create a pull request with the form validation whenever you have something working or if you are still stuck, create a pull request anyway and I can review it and possibly find where it is failing, thanks

**Comment by JoshuaVSherman** [comment]
@TheR3dErik Good afternoon, are you planing on having this task completed by Thursday? If not, please let me know. If I don't hear back from you by tomorrow, then i'll assume not and I'll do this myself so it can be included in the release for this Friday. Thanks.
