### ISSUE TITLE
Get rid of the "next" alpha versions of Babel

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#522]
"babel-core": "next",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-class-properties": "next",
    "babel-plugin-transform-decorators": "next",
    "babel-polyfill": "next",
    "babel-preset-env": "next",
    "babel-register": "next",

Update any necessary config changes that would be impacted

Use the aurelia-esnext-webpack skeleton as an example for doing this activity
https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman can you check the babel branch. I have downgraded the version but npm start raises an error in webpack. It seems there is a problem compiling the decorators. could be a problem with babel-plugin-transform-decorators. I'm not exactly sure. Any ideas would help.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves @LinuxBozo I fixed it
