### ISSUE TITLE
Everywhere where there is a checkbox in a webform should allow the user to click on the text next to the checkbox to check the box (not just clicking the box itself), please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#575]
@JoshuaVSherman commented on [Wed Aug 09 2017](https://github.com/WebJamApps/web-jam-back/issues/168)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman do you mean, a user can click the text next to a checkbox and still be able to check the box or clicking the text next to a checkbox shouldn't check the box.

**Comment by JoshuaVSherman** [comment]
Should

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman ok sure.

**Comment by JoshuaVSherman** [comment]
It is especially annoying on cell phone
