### ISSUE TITLE
Make these improvement to the volunteer dashboard

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#767]
* On the Volunteer Dashboard, make the header row in the table stationary as the user scrolls vertically
the table colums are not aligned properly anymore please fix, also borders colapsed is better thanks **DONE**
* Reload the page after user click the update volunteer preferences button - page does not reload, please fix

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman The latest commit fixes the stationary header but a reload of the page breaks the tests cases.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I tested this, but there are still issues, I noted them above in this task, please fix, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Fixed the alignment issues.
