### ISSUE TITLE
As a user, I want to reset my password (non-google email address account) if it is forgotten or lost

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#788]
* login has ability to reset password, which sends a new verification link to user 
* same page in frontend handles password reset with &form=reset 
* route put updates password, resetCode = '' and isPswdReset = false 
* user can ignore this request to reset password, and just login with their old password (which resets the resetCode to '' and the isPswdReset = false) 
* if email is a gmail or .vt.edu or .bi.vt.edu do not allow resert password or modify password

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I can be able to come up with a frontend implementation for this as long as there is a mailer daemon on the backend that sends verification links to the users email. I would suggest using sendgrid or another mail program.

**Comment by JoshuaVSherman** [comment]
Hey Danny, I already have this all fully coded in another repo, just
waiting for all the unit tests and refactoring activities to be completed.
So there isn't anything needed on this item. Thanks though.
https://github.com/VTbiocomplexity/backend
