### ISSUE TITLE
As a modern web developer, I want React running within the combined-front codebase (Aurelia Webpack Babel)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#823]
https://stackoverflow.com/questions/46282448/can-we-integrate-react-component-into-aurelia-project

* then create a new page with some sample react code that does something basic like prints "hello world" onto the page, to prove that React is actually working within the Aurelia/Webpack/Babel

**Comment by JoshuaVSherman** [comment]
@Coletrane Hey Cole, this is the next thing i'm interested in working on, so when are you available for an hour pairing to get started with this?

**Comment by JoshuaVSherman** [comment]
@Coletrane yo, yo, are you there? I thought you wanted to contribute again? please let me know

**Comment by JoshuaVSherman** [comment]
@Coletrane Hey, do you think you could do this issue soon!? if not, please let me know because I need to start working on React skills myself so I can get a new remote job (React is in very high demand right now!),  thanks

**Comment by JoshuaVSherman** [comment]
run react and redux within an aurelia

https://www.google.com/search?q=can+i+run+redux+with+aurelia&rlz=1C1CHBF_enUS764US764&oq=can+i+run+redux+with+aurelia&aqs=chrome..69i57.8494j0j8&sourceid=chrome&ie=UTF-8

**Comment by JoshuaVSherman** [comment]
https://github.com/wellyshen/react-cool-starter

https://github.com/arshdkhn1/ecommerce-site-template

**Comment by JoshuaVSherman** [comment]
https://github.com/workco/marvin

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves there are bunch of links and notes in this issue that may be helpful

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman great. I'll have a look at them.
