### ISSUE TITLE
Verify that bootstrap 4 is working as expected

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#858]
look at the aurelia skeleton and bootstrap 4 implementation
compare it to web jam front
create a test page with some bootstrap css in the html and see if it is working or not

**Comment by DannyMcwaves** [comment]
Hi @JoshuaVSherman 
Could you please provide more info on this issue. I can't seem to find the similar blocks of code in the charity.js and user-account.js files. thanks 😃

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I think this is a minor offense, lets please focus on the major ones. Thanks (pick a different issue please)
