### ISSUE TITLE
refactor all of the unit tests for slideshows to use the jasmine.clock rather than calling the real timer of chrome (tests are taking long to run because of this)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#969]
**HERE is example code**  

it('continues to check for expired token when there is a user defined', (done) => {
    jasmine.clock().install();
    let ruserObj = {name: 'howdy'};
    localStorage.setItem('rafterUser', JSON.stringify(ruserObj));
    document.body.innerHTML = '<div class="rafterLogout"></div>';
    rd.attached();
    jasmine.clock().tick(5500);
    //setTimeout(() => {
    done();
    jasmine.clock().uninstall();
    // }, 5500);
  });

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves hey Danny, if you choose to work on an issue that has someone else's name attached to it, please be sure to verify that they have not already started working on it, and put your name on the issue (so we don't both do the same thing), thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman sorry. my bad. I'd be sure to do that next time. I saw the issue I wanted to try it out if that'd be a better way than setTimeout and as it turns out it works better. So I decided to refactor the rest.

**Comment by JoshuaVSherman** [comment]
https://github.com/WebJamApps/combined-front/issues/1003
