### ISSUE TITLE
Make the following improvements to the charity.js

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/combined-front#978]
* Fix these 2 code-climate issues:
https://codeclimate.com/github/WebJamApps/combined-front/src/dashboard-child-routes/charity.js 
**DONE**

* the add additional manager field should set the email address to all lower case letters. **DONE**
  - all requests to the backend should be with this email address in lower case, use .toLowerCase()
  - allow the user to enter the email address in any case (so that it is not case sensitive from the UI)
* There should still be full test coverage on Charity.js

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves 
I create a new charity, then I click update charity
The update form populates, but the Validation Errors appear (even though the form is valid), please fix
Also, the add additional manager field does not populate with the email address as expected, please fix

Thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves  there is no longer test coverage on  setupValidation2() {
    ValidationRules
please fix, thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves your latest commit here breaks the app, going to revert it now
aurelia-logging-console.js?3f22:47 ERROR [app-router] TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at Function.Rules.set (webpack-internal:///81:15:16)
    at FluentEnsure.on (webpack-internal:///147:354:63)
    at FluentRuleCustomizer.on (webpack-internal:///147:102:34)
    at Charity.setupValidation2 (webpack-internal:///dashboard-child-routes/charity:220:708)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman I'll have a look at this tomorrow.
